[package]
name = "osg"
version = "0.1.0"
authors = ["IoP Ventures LLC <info@iop-ventures.com>", "Rache Bartmoss <bartmoss@tutanota.com>"]
edition = "2018"

[dependencies]
bincode = "*"
failure = "*"
log = "*"
keyvault = { path="../keyvault" }
serde = "*"
serde_derive = "*"
serde_json = "*"
