[package]
name = "mercury-home-node"
version = "0.1.0"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]

[dependencies]
bincode = "*"
capnp = "0.8"
capnp-rpc = "0.8"
clap = "2"
futures = "0.1"
log = "0.4"
log4rs = "0.8"
mercury-home-protocol = { path="../home-protocol" }
mercury-storage = { path="../storage" }
multiaddr = "*"
tokio-core = "0.1"
toml = "*"
failure = "*"
tokio-io = "*"
