[package]
name = "mercury-home-node"
version = "0.1.0"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]

[dependencies]
bincode = "*"
capnp = "0.8"
capnp-rpc = "0.8"
futures = "0.1"
mercury-home-protocol = { path="../home-protocol" }
mercury-storage = { path="../storage" }
multiaddr = "*"
multihash = "*"
tokio-core = "0.1"

tokio-io = "*"
