[package]
name = "mercury-home-node"
version = "0.1.0"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]

[dependencies]
bincode = "*"
clap = "2"
futures = "0.1"
log = "*"
log4rs = "*"
mercury-home-protocol = { path="../home-protocol" }
mercury-storage = { path="../storage" }
multiaddr = "*"
tokio-core = "0.1"
toml = "*"
failure = "*"
tokio-io = "*"
