[package]
name = "prometheus"
version = "0.1.0"
authors = ["IoP Ventures LLC <info@iop-ventures.com>", "Rache Bartmoss <bartmoss@tutanota.com>"]
edition = "2018"

[dependencies]
failure = "*"
log = "*"
morpheus_keyvault = { path="../morpheus_keyvault" }
serde = "*"
serde_derive = "*"
serde_json = "*"
