[package]
name = "prometheus"
version = "0.0.1-alpha1"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]
edition = "2018"

[dependencies]
failure = "*"
log = "*"
morpheus_keyvault = { path="../morpheus_keyvault" }
morpheus_storage = { path="../morpheus_storage" }
serde = "*"
#serde_bytes = "*"
serde_derive = "*"
# TODO these should be only binary dependencies, not needed for the library
dirs = "*"
log4rs = "*"
structopt = "*"
