[package]
name = "mercury-storage"
version = "0.1.0"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]
license = "LGPL-3.0+"

[dependencies]
#bip_dht = { git = "https://github.com/GGist/bip-rs" }
#bip_handshake = { git = "https://github.com/GGist/bip-rs" }
#bip_magnet = { git = "https://github.com/GGist/bip-rs" }
#bip_util = { git = "https://github.com/GGist/bip-rs" }
futures = "0.1"
futures-state-stream = "0.2"
ipfs-api = "0.4.0-alpha"
multibase = "0.6"
multihash = "*"
serde = "1"
serde_derive = "1"
serde_json = "1"
tokio = "*"
tokio-core = "0.1"
tokio-postgres = "0.3"
tokio-fs = "0.1"
tokio-threadpool = "0.1"
tokio-io = "*"
log = "*"
# multicodec = { git = "https://github.com/mudlee/rust-multicodec" }