[package]
name = "mercury-connect"
version = "0.1.0"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]

[dependencies]
clap = {version = "*", features = ["yaml"]}
capnp = "0.8"
capnp-rpc = "0.8"
futures = "0.1"
log = "0.4"
log4rs = "*"
mercury-home-protocol = { path="../home-protocol" }
mercury-storage = { path="../storage" }
multiaddr = "*"
serde = "*"
serde_derive = "*"
tokio-core = "0.1"
tokio-io = "*"
failure = "*"

