[package]
name = "mercury-home-protocol"
version = "0.1.0"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]

[build-dependencies]
capnpc = "0.8"

[dependencies]
bincode = "*"
capnp = "0.8"
capnp-rpc = "0.8"
futures = "0.1"
multiaddr = "*"
multihash = "*"
serde = "*"
serde_derive = "*"
tokio-core = "0.1"
