[package]
# TODO decide on naming. It seems this crate will be the home for the protocol and common utils. Suggestion: mercury-common.
name = "mercury-home-protocol"
version = "0.1.0"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]

[build-dependencies]
capnpc = "0.8"

[dependencies]
bincode = "*"
capnp = "0.8"
capnp-rpc = "0.8"
ed25519-dalek = "*"
futures = "0.1"
multiaddr = "*"
multihash = "*"
serde = "*"
serde_derive = "*"
signatory = { version="0.5", features=["std"] }
tokio-core = "0.1"
serde = "1"
serde_json = "1"
serde_derive = "1"