[package]
# TODO decide on naming. It seems this crate will be the home for the protocol and common utils. Suggestion: mercury-common.
name = "mercury-home-protocol"
version = "0.1.0"
authors = ["IoP Ventures LLC <info@iop-ventures.com>", "Rache Bartmoss <bartmoss@tutanota.com>"]
repository = "https://github.com/Internet-of-People/mercury-rust"
keywords = ["crypto", "wallet", "iop", "mercury", "morpheus", "prometheus", "vault", "key-vault"]
license = "LGPL-3.0+"
edition = "2018"

[build-dependencies]
capnpc = "*"

[dependencies]
bincode = "*"
bytes = "*"
capnp = "*"
capnp-rpc = "*"
failure= "*"
futures = "0.1"
log = "*"
multiaddr = "*"
multibase = "*"
multihash = "*"
tokio-core = "0.1"
tokio-io = "0.1"
serde = "*"
serde_derive = "*"
serde_json = "*"
structopt = "*"
toml = "*"

#osg = { path="../osg/osg" }
ed25519-dalek = { version="*", features=["std"] }
signatory = { version="*", features=["std"] }
signatory-dalek = "*"
#x25519-dalek = { version="*", default-features=false, features=["std"] }
