[package]
name = "mercury-home-protocol"
version = "0.1.0"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]

[build-dependencies]
capnpc = "0.8"

[dependencies]
capnp = "0.8"
capnp-rpc = "0.8"
futures = "0.1"
multiaddr = "*"
multihash = "*"
tokio-core = "0.1"
serde = "1"
serde_json = "1"
serde_derive = "1"