[package]
name = "mercury-common"
version = "0.1.0"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]

[build-dependencies]
capnpc = "0.8"

[dependencies]
capnp = "0.8"
futures = "0.1"
multiaddr = "*"
multihash = "*"
tokio-core = "0.1"
