[package]
name = "prometheusd"
version = "0.1.0"
authors = ["Rache Bartmoss <bartmoss@tutanota.com>"]
edition = "2018"

[dependencies]
actix-web = "*"
keyvault = { path="../keyvault" }
structopt = "*"
